[package]
name = "leetcode-SAO"
version = "0.0.1"
authors = ["huangjj27 <huangjj.27@qq.com>"]
edition = "2018"
license = "MIT"
description = "help to solve leetcode problems like SAO -- that you have only one life"

[dependencies]
